POST localhost:8081/events
content-type: application/json

{
  "name": "Test Event 2",
  "description": "A second test event for API testing",
  "location": "Another test area",
  "dateTime": "2025-08-22T14:58:00Z"
}