POST localhost:8081/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTYxNTIxNjksInVzZXJJZCI6MX0.lN-YXEQoYUGP8Ys0UKIA7o32n4q7nR21kkNWqw1z20k

{
  "name": "Test Event",
  "description": "A test event for API testing",
  "location": "Test area",
  "dateTime": "2025-08-25T19:02:00Z"
}