PUT localhost:8081/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTYyMTY4NTUsInVzZXJJZCI6MX0.9MkIJFD0TRr6d_78md4EUHnsOKIG7DPqx3jFh74sBN4

{
    "name": "Updated Test Event",
    "description": "An updated description for the test event",
    "location": "Updated test area",
    "dateTime": "2025-08-22T15:00:00Z"
}